<div class="dropdown float-right">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <?php echo $locale->_('lang') ?>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="<?php echo $_SERVER['REQUEST_URI'] . "?locale=en" ?>">English</a>
        <a class="dropdown-item" href="<?php echo $_SERVER['REQUEST_URI'] . "?locale=fr" ?>">French</a>
        <a class="dropdown-item" href="<?php echo $_SERVER['REQUEST_URI'] . "?locale=hi" ?>">Hindi</a>
        <a class="dropdown-item" href="<?php echo $_SERVER['REQUEST_URI'] . "?locale=ja" ?>">Japanese</a>
    </div>
</div>
<h2><?php echo $locale->_('login'); ?></h2>
<?php echo $this->tag->form(""); ?>

<p>
    <label for="email"><?php echo $locale->_('email'); ?></label>
    <?php echo $this->tag->textField("email"); ?>
</p>

<p>
    <label for="password"><?php echo $locale->_('password'); ?></label>
    <?php echo $this->tag->textField("password"); ?>
</p>
<p>

    <?php
    echo $message;
    echo $this->tag->submitButton([$locale->_('login'), "class" => "btn btn-primary"]); ?>
</p>

</form>
<?php echo $this->tag->linkTo('user/signup', $locale->_('signup')); ?>