<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $locale->_('order'); ?></title>
</head>

<body>
    <div class="dropdown float-right">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <?php echo $locale->_('lang') ?>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="<?php echo $_SERVER['REQUEST_URI'] . "&locale=en" ?>">English</a>
            <a class="dropdown-item" href="<?php echo $_SERVER['REQUEST_URI'] . "&locale=fr" ?>">French</a>
            <a class="dropdown-item" href="<?php echo $_SERVER['REQUEST_URI'] . "&locale=hi" ?>">Hindi</a>
            <a class="dropdown-item" href="<?php echo $_SERVER['REQUEST_URI'] . "&locale=ja" ?>">Japanese</a>
        </div>
    </div>
    <?php echo $this->tag->linkTo(["/user", $locale->_('logout'), 'class' => 'btn btn-success']); ?>
    <h2><?php ?></h2>

    <?php echo $this->tag->form(""); ?>

    <p>
        <label for="name"><?php echo $locale->_('name') ?></label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="address"><?php echo $locale->_('address') ?></label>
        <?php echo $this->tag->textArea("address"); ?>
    </p>

    <p>
        <label for="zip"><?php echo $locale->_('zip') ?></label>
        <?php echo $this->tag->textField("zip"); ?>
    </p>
    <select name="product">
        <?php
        if ($products)
            if ($products->count() > 0) {
                foreach ($products as $product) { ?>

                <option value='<?php echo $product->name; ?>' name='procuct'><?php echo $product->name; ?></option>
        <?php }
            }; ?>
    </select>
    <p>
        <label for="quantity"><?php echo $locale->_('quantity') ?></label>
        <?php echo $this->tag->textField("quantity"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton([$locale->_('add'), "class" => "btn btn-primary"]);
        echo $errorMessage;
        ?>
    </p>

    </form>
</body>

</html>